import React from 'react';

/**
 * BlogGridBottom Component
 * 
 * Clones the final set of blog post cards in the grid encompassing topics like 
 * "Peptide vs Protein", "What are Peptides?", and "What are Collagen Peptides?".
 * 
 * Clinical-Scientific Minimalist style.
 */

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  imageUrl: string;
  link: string;
  alt: string;
}

const blogPosts: BlogPost[] = [
  {
    id: 'peptide-vs-protein',
    title: 'PEPTIDE VS PROTEIN: WHAT\'S THE DIFFERENCE?',
    excerpt: 'On this page Introduction to Peptides and Proteins What are Peptides? What are Proteins? Key Differences Roles in the Body Medical Applications Conclusion FAQs For more background, see what are...',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/230936c2-4e5c-43af-beb9-b9e321d2e7bf-peptidesskin-com/assets/images/myogenesis-muscle-cell-research-peptides-article-h-14.webp',
    link: '#',
    alt: 'Scientific comparison between peptide and protein molecules'
  },
  {
    id: 'what-are-peptides',
    title: 'WHAT ARE PEPTIDES?',
    excerpt: 'Peptides are essential tools in modern biochemistry, allowing researchers to probe cellular signaling, enzymatic pathways, and protein interactions. This 2025 guide explains how research peptides are defined, synthesized, purified, and...',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/230936c2-4e5c-43af-beb9-b9e321d2e7bf-peptidesskin-com/assets/images/peptides-for-healing-regeneration-banner-15.webp',
    link: '#',
    alt: 'Microscopic view of peptide chains'
  },
  {
    id: 'what-are-collagen-peptides',
    title: 'WHAT ARE COLLAGEN PEPTIDES?',
    excerpt: 'Collagen peptides are low-molecular-weight fragments generated by enzymatic hydrolysis of native collagen and widely used as tools in ECM and fibroblast research. This technical review explains their Gly-X-Y motif, Dalton...',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/230936c2-4e5c-43af-beb9-b9e321d2e7bf-peptidesskin-com/assets/images/research-peptides-cellular-homeostasis-lab-hero-16.webp',
    link: '#',
    alt: 'Structure of collagen peptides in a research context'
  }
];

export default function BlogGridBottom() {
  return (
    <section className="section bg-white py-[60px]">
      <div className="container px-10 max-w-[1400px] mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[30px]">
          {blogPosts.map((post) => (
            <div key={post.id} className="blog-card flex flex-col group">
              {/* Image Wrapper */}
              <div className="blog-card-img-wrapper border border-[#e5e5e5] aspect-video overflow-hidden mb-[15px]">
                <a href={post.link} className="block w-full h-full">
                  <img
                    src={post.imageUrl}
                    alt={post.alt}
                    className="blog-card-img w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  />
                </a>
              </div>

              {/* Content */}
              <div className="blog-card-content flex flex-col">
                <a href={post.link} className="hover:opacity-80 transition-opacity">
                  <h3 className="text-[20px] font-semibold leading-[1.3] uppercase mt-0 mb-[10px] tracking-normal">
                    {post.title}
                  </h3>
                </a>

                <div className="mb-[15px]">
                  <p className="text-[14px] leading-[1.6] text-[#000000] m-0 inline">
                    {post.excerpt}
                  </p>
                  <a 
                    href={post.link} 
                    className="link-read-more text-[14px] text-[#d11a2a] hover:underline ml-1 whitespace-nowrap"
                  >
                    Read more...
                  </a>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}